services:
  - type: web
    name: anagrammatic
    env: python
    buildCommand: pip install poetry && poetry install
    startCommand: gunicorn anagrammatic:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.8.0
      - key: FLASK_ENV
        value: production 